apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-deployment
  labels:
    app: survey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey
  template:
    metadata:
      labels:
        app: survey
    spec:
      containers:
        - name: survey-container
          image: tejaswi0502/ass2-dockerimage-dt:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
