apiVersion: v1
kind: Service
metadata:
  name: survey-service
spec:
  selector:
    app: survey
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32702
